### ISSUE TITLE
WindowView not overlaying keyboard

### ISSUE THREAD

**Issue by greenmood** [hfossli/AGWindowView#12]
Hi,

First of all, thanks for a great job with this library. There's one thing, i can't understand how to make it with your library. Imagine following situation: There's a stack of view controllers, by clicking next button in one of them, next view controller is opened. When this second vc is opened, some textfield in that controller becomes first responder. So keyboard becomes visible. The problem here, is that AGWindowView is not overlaying this keyboard. It's keyboard overlaying AGWindowView. 

If i get it correct, AGwindowView uses keyWindow, which is usually the first window in UIApplication windows array. And when keyboard shows, Additional window(actually UITextEffectWindow) is added to windows array. So UITextEffectWindow is now on top of key window.

**Comment by hfossli** [comment]
Won't fix
