### ISSUE TITLE
AirPlay device picker broken on iOS8 iPad

### ISSUE THREAD

**Issue by viljamik** [hfossli/AGWindowView#18]
When I created a MPVolumeView with showsRouteButton=YES and added it inside a view in AGWindowView, I can manipulate volume etc. but when I press the AirPlay button, the device picker window does not appear.

This only happens on iOS 8 and iPad. iPhone seems to have a different style popup and it is working fine.

Any idea why this is happening? Might be a platform bug too because on iOS7 it worked just fine.

**Comment by hfossli** [comment]
The UIPopoverController from Apple has always been very buggy and behaving very differently on different versions and devices. 

I'm sorry to hear that AGWindowView is not compliant with the combo mentioned. 

Maybe you could hide AGWindowView while the popover is being displayed?

**Comment by viljamik** [comment]
Hi,

Thank you for your quick reply. Yeah, I believe this is really Apple's issue on iOS8 iPad(s). Luckily, in my case I can try to fix the UI in a way that the MPVolumeView will be positioned in a UIView other than AGWindowView so it will work then.

Thank you for your help and for this great library! I'll be using it elsewhere at least.

**Comment by hfossli** [comment]
Ok cool. AGWindowView is built as a robust last resort alternative, but it will definitely not be compatible with all of UIKit's assumptions about view hierarchy (like the popover in ipad ios 8).

**Comment by hfossli** [comment]
Won't fix.
